/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vision;

/**
 *
 * @author Daniel
 */
public class JfrmMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form NewMDIApplication
     */
    public JfrmMenuPrincipal() {
        initComponents();
        this.setExtendedState(JfrmMenuPrincipal.MAXIMIZED_BOTH);
        this.setTitle("Sistema de Reservas de Hotel e Gestão de Vendas - Hotel Teste");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jLabelPessoa = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelCpf = new javax.swing.JLabel();
        jLabelRg = new javax.swing.JLabel();
        jLabelAcesso = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        mnusisreserva = new javax.swing.JMenu();
        mnuarquivo = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        mnureservas = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        mnuconsultas = new javax.swing.JMenu();
        mnuconfiguracoes = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        mnuferramentas = new javax.swing.JMenu();
        mnuajuda = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        mnusair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(255, 204, 102));

        jLabelPessoa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPessoa.setText("jLabel1");
        escritorio.add(jLabelPessoa);
        jLabelPessoa.setBounds(20, 20, 100, 14);

        jLabelNome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelNome.setText("jLabel2");
        escritorio.add(jLabelNome);
        jLabelNome.setBounds(20, 40, 100, 14);

        jLabelCpf.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCpf.setText("jLabel3");
        escritorio.add(jLabelCpf);
        jLabelCpf.setBounds(20, 60, 100, 14);

        jLabelRg.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelRg.setText("jLabel4");
        escritorio.add(jLabelRg);
        jLabelRg.setBounds(20, 80, 100, 14);

        jLabelAcesso.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelAcesso.setText("jLabel5");
        escritorio.add(jLabelAcesso);
        jLabelAcesso.setBounds(20, 100, 100, 14);

        mnusisreserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Arquivos/inicio.png"))); // NOI18N
        mnusisreserva.setMnemonic('f');
        mnusisreserva.setText("SisReserva");
        menuBar.add(mnusisreserva);

        mnuarquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Arquivos/arquivo.png"))); // NOI18N
        mnuarquivo.setText("Arquivo");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Apartamentos");
        contentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItemActionPerformed(evt);
            }
        });
        mnuarquivo.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Produtos");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        mnuarquivo.add(aboutMenuItem);

        menuBar.add(mnuarquivo);

        mnureservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Arquivos/reserva.png"))); // NOI18N
        mnureservas.setMnemonic('h');
        mnureservas.setText("Reservas");

        jMenuItem1.setText("Reservas e Consumos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnureservas.add(jMenuItem1);

        jMenuItem2.setText("Clientes");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mnureservas.add(jMenuItem2);

        jMenuItem3.setText("Pagamentos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mnureservas.add(jMenuItem3);

        menuBar.add(mnureservas);

        mnuconsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Arquivos/consulta.png"))); // NOI18N
        mnuconsultas.setText("Consultas");
        menuBar.add(mnuconsultas);

        mnuconfiguracoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Arquivos/configuracoes.png"))); // NOI18N
        mnuconfiguracoes.setText("Configurações");

        jMenuItem4.setText("Usuários e Acessos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        mnuconfiguracoes.add(jMenuItem4);

        menuBar.add(mnuconfiguracoes);

        mnuferramentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Arquivos/ferramentas (1).png"))); // NOI18N
        mnuferramentas.setText("Ferramentas");
        menuBar.add(mnuferramentas);

        mnuajuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Arquivos/ajuda.png"))); // NOI18N
        mnuajuda.setText("Ajuda");

        jMenuItem5.setText("A respeito...");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        mnuajuda.add(jMenuItem5);

        jMenuItem6.setText("Ajuda");
        mnuajuda.add(jMenuItem6);

        menuBar.add(mnuajuda);

        mnusair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Arquivos/sair2.png"))); // NOI18N
        mnusair.setText("Sair");
        mnusair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnusairMouseClicked(evt);
            }
        });
        mnusair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnusairActionPerformed(evt);
            }
        });
        menuBar.add(mnusair);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItemActionPerformed
        // TODO add your handling code here:
        JfrmApto form = new JfrmApto();
        escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_contentMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        // TODO add your handling code here:
        JfrmProduto frm = new JfrmProduto();
        escritorio.add(frm);
        frm.toFront();
        frm.setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void mnusairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnusairActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mnusairActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JfrmCliente frm = new JfrmCliente();
        escritorio.add(frm);
        frm.toFront();
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        JfrmTrabalhador frm = new JfrmTrabalhador();
        escritorio.add(frm);
        frm.toFront();
        frm.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void mnusairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnusairMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_mnusairMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JfrmReserva frm = new JfrmReserva();
        escritorio.add(frm);
        frm.toFront();
        frm.setVisible(true);
        JfrmReserva.txtIdTrabalhador.setText(jLabelPessoa.getText());
        JfrmReserva.txtFuncionario.setText(jLabelNome.getText());
        JfrmReserva.idusuario=Integer.parseInt(jLabelPessoa.getText());
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        try {
            JfrmPagamento frmp = new JfrmPagamento();
            escritorio.add(frmp);
            frmp.toFront();
            frmp.setVisible(true);
        } catch (Exception e) {
            System.out.println("Erro: " + e.getClass() + e.getMessage());
        }
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here
       JfrmSobre sobre = new JfrmSobre();
       sobre.toFront();
       sobre.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfrmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    public static javax.swing.JDesktopPane escritorio;
    public static javax.swing.JLabel jLabelAcesso;
    public static javax.swing.JLabel jLabelCpf;
    public static javax.swing.JLabel jLabelNome;
    public static javax.swing.JLabel jLabelPessoa;
    public static javax.swing.JLabel jLabelRg;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnuajuda;
    public static javax.swing.JMenu mnuarquivo;
    public static javax.swing.JMenu mnuconfiguracoes;
    private javax.swing.JMenu mnuconsultas;
    private javax.swing.JMenu mnuferramentas;
    private javax.swing.JMenu mnureservas;
    private javax.swing.JMenu mnusair;
    private javax.swing.JMenu mnusisreserva;
    // End of variables declaration//GEN-END:variables

}
